name: CI for C project

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc make clang-format

      - name: Check code formatting
        run: |
          set -e
          find . -regex '.*\.[ch]' -exec clang-format -style=LLVM -i {} +
          find . -regex '.*\.[ch]' -exec clang-format -style=LLVM --dry-run --Werror {} +

      - name: Build project
        run: |
          set -e
          make


      - name: Run tests
        run: |
          set -e
          make run